version: '3'
services:
  server:
    image: "anirudhgoyal/server:latest"
    ports:
      - "5000:5000"
    depends_on:
      - redis
    volumes:
      - .:/atlan-challenge
  redis:
    image: "redis:alpine"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdata:/data
volumes:
  redisdata:



  